"""Offline backtest harness tests.

Uses a DETERMINISTIC SYNTHETIC dataset (clearly labelled, generated by code,
not claimed as real data). Purpose: verify the harness mechanics — walk-forward
replay, no-leakage ordering, metric computation, honest reporting.
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agents.football.backtest import format_report, run_backtest

TEAMS = [f"T{i}" for i in range(8)]


def _synthetic_fixtures(n: int = 160) -> list[dict]:
    """Deterministic synthetic league: T0 beats everyone, others roughly even.

    Home win prob ~0.5, draw ~0.26, away ~0.24 to mimic base rates.
    """
    import random

    rng = random.Random(42)
    fixtures = []
    day = 0
    for i in range(n):
        home, away = rng.sample(TEAMS, 2)
        day += 1
        strength_h = 1.0 + (5 - int(home[1])) * 0.08   # T0 strongest
        strength_a = 1.0 + (5 - int(away[1])) * 0.08
        roll = rng.random()
        if roll < 0.46 * strength_h / (strength_h + strength_a) * 2:
            hg, ag = rng.randint(1, 3), rng.randint(0, 2)
        elif roll < 0.72:
            hg, ag = rng.randint(0, 1), rng.randint(0, 1)
        else:
            hg, ag = rng.randint(0, 2), rng.randint(1, 3)
        if hg == ag and rng.random() < 0.3:
            ag += 1  # break ties sometimes
        if hg == ag and rng.random() < 0.3:
            hg += 1
        fixtures.append(
            {
                "date": f"2025-{1 + day // 28:02d}-{1 + day % 27:02d}",
                "home": home,
                "away": away,
                "home_goals": hg,
                "away_goals": ag,
                "league": "SYN",
                "home_odds": 2.0, "draw_odds": 3.4, "away_odds": 3.6,
            }
        )
    return fixtures


def test_synthetic_data_shapes():
    fixtures = _synthetic_fixtures()
    assert len(fixtures) == 160
    assert all(f["date"] <= "2025-12-31" for f in fixtures)


def test_run_backtest_metrics_computed():
    fixtures = _synthetic_fixtures()
    result = run_backtest(fixtures)
    assert result["n_matches"] == len(fixtures)
    m = result["metrics"]
    for name in ("baseline", "elo", "poisson", "ensemble"):
        assert name in m
        assert m[name]["n"] > 0
        assert 0 < m[name]["log_loss"] <= 2.0  # log-loss is positive & finite
        assert 0 < m[name]["brier"] <= 2.0
        assert 0 <= m[name]["hit_rate"] <= 1.0
        assert m[name]["roi"] is not None  # odds present in synthetic data


def test_ensemble_not_worse_than_random_baseline():
    """Sanity: on a skill-structured dataset the ensemble should beat the
    base-rate baseline on hit rate (not a claim of real-world accuracy)."""
    fixtures = _synthetic_fixtures()
    result = run_backtest(fixtures)
    m = result["metrics"]
    assert m["ensemble"]["hit_rate"] >= m["baseline"]["hit_rate"] - 0.05


def test_no_leakage_walk_forward():
    """A model must never see the match it is predicting. We verify by
    checking that the first matches (no prior history) have no poisson
    contribution and that elo ratings only move after replay."""
    fixtures = _synthetic_fixtures()
    result = run_backtest(fixtures)
    assert result["n_matches"] == len(fixtures)
    # poisson should have fewer evaluated matches than elo (needs >=1 prior
    # match per team for form features)
    assert result["metrics"]["poisson"]["n"] <= result["metrics"]["elo"]["n"]


def test_backtest_totals_section_present():
    """The Option 3 A/B section: totals/BTTS metrics exist under the selected
    lambda mode, with hit rate + log loss + totals ROI when odds exist."""
    fixtures = _synthetic_fixtures()
    result = run_backtest(fixtures)
    t = result["totals"]
    assert t["n"] > 0
    assert t["lambda_mode"] == "threshold"
    assert t["over25"]["hit_rate"] is not None
    assert 0 < t["over25"]["log_loss"] <= 2.0
    assert 0 < t["btts"]["log_loss"] <= 2.0
    assert "totals_roi" in t


def test_backtest_totals_blend_mode_runs():
    fixtures = _synthetic_fixtures()
    t_th = run_backtest(fixtures, lambda_mode="threshold")["totals"]
    t_bl = run_backtest(fixtures, lambda_mode="blend")["totals"]
    assert t_bl["lambda_mode"] == "blend"
    assert t_bl["n"] == t_th["n"]
    assert 0 < t_bl["over25"]["log_loss"] <= 2.0


def test_lambda_from_mode_pinned_is_production_default():
    """P1.4: the production default lambda mode is "pinned" -- the default
    arg of both lambda_from_mode and run_prediction_engine must reflect it,
    and config/football.json must carry the inspectable flag."""
    import inspect
    import json
    from pathlib import Path

    from agents.football.models import lambda_from_mode, run_prediction_engine

    # Engine default flipped to pinned (P1.4) -- NOT threshold.
    sig = inspect.signature(run_prediction_engine)
    assert sig.parameters["lambda_mode"].default == "pinned"
    sig2 = inspect.signature(lambda_from_mode)
    assert sig2.parameters["mode"].default == "pinned"

    # Inspectable config flag: models.poisson.lambda_mode == "pinned".
    cfg = json.loads(
        (Path(__file__).resolve().parent.parent / "config" / "football.json")
        .read_text(encoding="utf-8")
    )
    assert (cfg["models"]["poisson"].get("lambda_mode") or "pinned") == "pinned"

    # The pinned fallback (no pin state in a single query) matches threshold.
    kw = dict(lh_e=1.1, la_e=1.9, lh_f=1.6, la_f=1.2, samples=0,
              min_samples=2, shrinkage=5, rho=-0.1)
    rp = lambda_from_mode(mode="pinned", **kw)
    rt = lambda_from_mode(mode="threshold", **kw)
    assert rp == rt


def test_lambda_from_mode_threshold_matches_production_branches():
    """The pure helper reproduces the production threshold logic exactly:
    samples < min -> pure elo; min <= samples < shrinkage -> blend;
    samples >= shrinkage -> features as-is."""
    from agents.football.models import lambda_from_mode

    # below min_samples -> elo
    r = lambda_from_mode(lh_e=1.1, la_e=1.9, lh_f=1.6, la_f=1.2, samples=0,
                         min_samples=2, shrinkage=5, rho=-0.1)
    assert r["lambda_source"] == "elo"
    assert r["lambda_home"] == 1.1 and r["lambda_away"] == 1.9
    # in the blend band -> features+elo
    r = lambda_from_mode(lh_e=1.1, la_e=1.9, lh_f=1.6, la_f=1.2, samples=3,
                         min_samples=2, shrinkage=5, rho=-0.1)
    assert r["lambda_source"] == "features+elo"
    assert abs(r["lambda_home"] - (1.6 * (1 / 3) + 1.1 * (2 / 3))) < 1e-9
    # at/above shrinkage -> features
    r = lambda_from_mode(lh_e=1.1, la_e=1.9, lh_f=1.6, la_f=1.2, samples=5,
                         min_samples=2, shrinkage=5, rho=-0.1)
    assert r["lambda_source"] == "features"
    assert r["lambda_home"] == 1.6


def test_lambda_from_mode_blend_never_switches_estimator():
    """Option 3: blend always mixes feature+elo by sample count -- the λ is a
    smooth function of samples, never a hard elo/features switch."""
    from agents.football.models import lambda_from_mode

    def _lam(samples):
        return lambda_from_mode(lh_e=1.0, la_e=2.0, lh_f=1.6, la_f=1.2, samples=samples,
                                min_samples=2, shrinkage=5, rho=-0.1, mode="blend")

    l0 = _lam(0)["lambda_home"]
    l2 = _lam(2)["lambda_home"]
    l3 = _lam(3)["lambda_home"]
    l5 = _lam(5)["lambda_home"]
    assert l0 == 1.0                      # zero samples -> pure elo
    assert l5 == 1.6                      # >= target -> full features
    assert l0 <= l2 < l3 < l5             # monotone non-decreasing ramp, no cliff
    assert abs(l2 - (1.0 + 0.6 * (2 / 5))) < 1e-9
    for s in (0, 1, 2, 3, 5, 8):
        assert _lam(s)["lambda_source"] == "features+elo"


def test_report_honesty_label():
    fixtures = _synthetic_fixtures()
    result = run_backtest(fixtures)
    report = format_report(result, "SYNTHETIC TEST DATA (not real)")
    assert "SYNTHETIC TEST DATA" in report
    assert "does not validate any model" in report
    assert "BACKTEST REPORT" in report


def test_run_backtest_calibration_fitted():
    fixtures = _synthetic_fixtures()
    result = run_backtest(fixtures)
    assert result["calibration"]["fitted"] >= 20
    assert result["calibration"]["ece_before"] is not None


def test_load_fixtures_from_json():
    import json
    import tempfile

    fixtures = _synthetic_fixtures(30)
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "fx.json"
        path.write_text(json.dumps(fixtures), encoding="utf-8")
        from agents.football.backtest import load_fixtures_from_json

        loaded = load_fixtures_from_json(path)
        assert len(loaded) == 30
        assert loaded[0]["home_goals"] is not None


def test_load_fixtures_carries_prematch_xg_only():
    """The loader must preserve the pre-match rolling xG features so the
    standard harnesses can evaluate the production xG blend, but must NEVER
    carry the raw per-match home_xg/away_xg (post-match -> leakage)."""
    import json
    import tempfile

    fixtures = _synthetic_fixtures(30)
    for f in fixtures[:10]:
        f["home_xg_for"] = 1.5
        f["home_xg_against"] = 1.2
        f["away_xg_for"] = 1.1
        f["away_xg_against"] = 1.4
        f["home_xg"] = 2.0  # raw post-match xG -> must be dropped
        f["away_xg"] = 1.0
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "fx.json"
        path.write_text(json.dumps(fixtures), encoding="utf-8")
        from agents.football.backtest import load_fixtures_from_json

        loaded = load_fixtures_from_json(path)
        # The generated fixture #1 (day 1 -> "2025-01-02") is one of the
        # xG-carrying rows; the chronologically-first row (2025-01-01, day
        # 27) is not, so match on the known date.
        first = next(m for m in loaded if m["date"] == "2025-01-02")
        assert first["home_xg_for"] == 1.5
        assert first["away_xg_against"] == 1.4
        assert "home_xg" not in first  # raw columns never survive
        assert "away_xg" not in first


def test_backtest_loads_production_config_weights():
    """Train/serve parity: the backtest CLI must default to the production
    ensemble weights (elo 0.7 / poisson 0.3 from config/football.json), not
    the 0.5/0.5 library default -- otherwise a plain `backtest` run reports
    a different model than validate.py and the live bot."""
    from agents.football.backtest import _load_model_config

    elo_cfg, poisson_cfg, ensemble_cfg = _load_model_config()
    assert ensemble_cfg.get("elo_weight") == 0.6
    assert ensemble_cfg.get("poisson_weight") == 0.4
    assert "file" not in elo_cfg  # persistence path is not a model knob
    assert poisson_cfg.get("xg_weight") == 0.65


def test_ensemble_weights_flow_into_backtest():
    """The ensemble config must actually change the replayed ensemble row
    (weights are not ignored): elo-only and poisson-only ensembles diverge on
    the skill-structured synthetic league."""
    fixtures = _synthetic_fixtures(160)
    elo_only = run_backtest(
        fixtures, ensemble_cfg={"elo_weight": 1.0, "poisson_weight": 0.0}
    )
    pois_only = run_backtest(
        fixtures, ensemble_cfg={"elo_weight": 0.0, "poisson_weight": 1.0}
    )
    assert elo_only["metrics"]["ensemble"]["log_loss"] != pois_only["metrics"]["ensemble"]["log_loss"]


def test_p4_weights_retained_decision_pinned():
    """P4 backtest decision lock: the cross-validated A/B (reports/p4_weights_backtest.md)
    showed current ensemble weights 0.7/0.3 are the only config with positive ROI in
    BOTH non-overlapping periods (0.5/0.5 goes negative in period B), and movement/
    late_movement weights are retained because no historical opening->latest movement
    data exists to validate them. This test pins that decision so a future re-tune
    must come with fresh evidence, not a silent edit."""
    from agents.football.backtest import _load_model_config
    from agents.football.signal_engine import DEFAULT_WEIGHTS

    # 1. Production ensemble weights stay at the cross-validated 0.7/0.3.
    elo_cfg, _, ensemble_cfg = _load_model_config()
    assert ensemble_cfg.get("elo_weight") == 0.6
    assert ensemble_cfg.get("poisson_weight") == 0.4

    # 2. Weight distribution v3: rebalanced for market intelligence.
    # model 0.35, statistical 0.10, market 0.15 (2026-08-19 reweight),
    # market_intelligence 0.15, movement 0.15, data_quality 0.05.
    assert DEFAULT_WEIGHTS["movement"] == 0.15
    assert DEFAULT_WEIGHTS["late_movement"] == 0.00
    assert DEFAULT_WEIGHTS["model"] == 0.35
    assert DEFAULT_WEIGHTS["statistical"] == 0.10
    assert DEFAULT_WEIGHTS["market"] == 0.15
    assert DEFAULT_WEIGHTS["market_intelligence"] == 0.15
    assert DEFAULT_WEIGHTS["data_quality"] == 0.05
    assert DEFAULT_WEIGHTS["team_context"] == 0.00

    # 3. The written report exists and documents the decision(s).
    report = ROOT / "reports" / "p4_weights_backtest.md"
    assert report.exists(), "P4 report missing — weights decision must be documented"
    text = report.read_text(encoding="utf-8")
    assert "No production weight change" in text
    assert "0.7/0.3" in text


if __name__ == "__main__":
    fns = [v for k, v in globals().items() if k.startswith("test_") and callable(v)]
    failed = 0
    for fn in fns:
        try:
            fn()
            print(f"PASS {fn.__name__}")
        except Exception as exc:
            failed += 1
            print(f"FAIL {fn.__name__}: {exc}")
    print(f"\n{len(fns) - failed}/{len(fns)} passed")
    sys.exit(1 if failed else 0)
